# Generated by Django 5.2 on 2025-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money_Parse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='unnamed', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
