# Generated by Django 5.2 on 2025-04-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Money_Parse', '0005_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(max_length=20),
        ),
    ]
