# Generated by Django 5.1.6 on 2025-04-20 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('goals', models.TextField(blank=True)),
                ('categories', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
